-
  - b
  - bʲ
-
  - c
  - k
-
  - dʒ
-
  - dʲ
  - d̪
-
  - f
  - fʲ
-
  - j
-
  - m
  - ɱ
  - mʲ
-
  - n̪
  - ɲ
  - ŋ
-
  - p
  - pʲ
-
  - r
  - rʲ
-
  - sʲ
  - s̪
-
  - t̪s̪
  - tsʲ
-
  - tʃ
-
  - tʲ
  - t̪
-
  - v
  - vʲ
-
  - x
  - ç
-
  - zʲ
  - z̪
-
  - ɫ
  - ʎ
-
  - ʃ
-
  - ʒ
-
  - ɟ
  - ɡ
-
  - i
-
  - a
-
  - ɤ
-
  - ɔ
-
  - ɛ
-
  - u
-
  - o
