-
  - P
-
  - B
-
  - F
-
  - V
-
  - TH
-
  - DH
-
  - T
-
  - D
-
  - CH
-
  - JH
-
  - SH
-
  - ZH
-
  - S
-
  - Z
-
  - R
-
  - M
-
  - N
-
  - NG
-
  - L
-
  - G
-
  - K
-
  - HH
-
  - AH1
  - AH2
  - AH0
-
  - ER1
  - ER2
  - ER0
-
  - UH1
  - UH2
  - UH0
-
  - IH1
  - IH2
  - IH0
-
  - AY1
  - AY2
  - AY0
-
  - OY1
  - OY2
  - OY0
-
  - OW1
  - OW2
  - OW0
-
  - AW1
  - AW2
  - AW0
-
  - AA1
  - AA2
  - AA0
-
  - AO1
  - AO2
  - AO0
-
  - IY1
  - IY2
  - IY0
-
  - Y
-
  - AE1
  - AE2
  - AE0
-
  - EH1
  - EH2
  - EH0
-
  - EY1
  - EY2
  - EY0
-
  - UW1
  - UW2
  - UW0
-
  - W
