-
  - b
-
  - d
-
  - dʒ
-
  - h
-
  - j
-
  - j̰
-
  - c
  - cʼ
  - k
  - kʷ
  - kʷʼ
  - kʼ
-
  - l
-
  - m
-
  - n
  - ɲ
  - ŋ
-
  - p
-
  - r
-
  - s
-
  - sʼ
-
  - t
-
  - tʃ
-
  - w
-
  - z
-
  - ɓ
-
  - ɗ
-
  - ɟ
  - ɡ
  - ɡʷ
-
  - ɸ
-
  - ɽ
-
  - ʃ
-
  - ʔ
-
  - aj˥
  - aj˥˦
  - aj˩
-
  - aw˥
  - aw˥˦
  - aw˩
-
  - aː˥
  - aː˥˦
  - aː˩
  - a˥
  - a˥˦
  - a˩
  - ə˥
  - ə˩
-
  - eː˥
  - eː˥˦
  - eː˩
  - e˥
  - e˥˦
  - e˩
  - ɛ˥
  - ɛ˥˦
  - ɛ˩
-
  - iː˥
  - iː˥˦
  - iː˩
  - ɪ˥
  - ɪ˥˦
  - ɪ˩
-
  - uː˥
  - uː˥˦
  - uː˩
  - ʊ˥
  - ʊ˥˦
  - ʊ˩
-
  - ɔ˥
  - ɔ˩
  - oː˥
  - oː˥˦
  - oː˩
  - o˥
  - o˩
