-
  - p
  - pː
-
  - pʰ
  - pʰː
-
  - b
  - bː
-
  - bʱ
  - bʱː
-
  - t̪
  - t̪ː
-
  - t̪ʰ
  - t̪ʰː
-
  - d̪
  - d̪ː
-
  - d̪ʱ
  - d̪ʱː
-
  - tʃ
  - tʃː
-
  - tʃʰ
  - tʃʰː
-
  - dʒ
  - ʒ
  - dʒː
-
  - dʒʱ
  - dʒʱː
-
  - ʈ
  - ʈː
-
  - ʈʰ
  - ʈʰː
-
  - ɖ
  - ɖː
-
  - ɖʱ
  - ɖʱː
-
  - k
  - kː
-
  - q
  - qː
-
  - kʰ
  - kʰː
-
  - ɡ
  - ɡː
-
  - ɣ
-
  - x
-
  - ɡʱ
  - ɣ
  - ɡʱː
-
  - m
  - mʱ
  - mː
-
  - n̪
  - n̪ʱ
  - n̪ː
-
  - ɲ
-
  - ɳ
  - ɳː
-
  - ŋ
-
  - l̪
  - l̪ʱ
  - l̪ː
-
  - f
  - fː
-
  - ʋ
  - ʋː
-
  - s̪
  - s̪ː
-
  - z̪
  - z̪ː
-
  - ʂ
  - ʂː
  - ʃ
  - ʃː
-
  - r
  - rː
-
  - ɽ
-
  - ɽʱ
-
  - ɾ
-
  - w
  - wː
-
  - j
  - jː
-
  - ɦ
-
  - æː
  - æ
-
  - æ̃
-
  - aː
-
  - ãː
-
  - eː
-
  - ẽː
-
  - iː
-
  - ĩː
-
  - oː
-
  - õː
-
  - uː
-
  - ũː
-
  - ɔ
  - ɔː
-
  - ɔ̃
  - ɔ̃ː
-
  - ə
  - əː
-
  - ə̃
-
  - ɛ
  - ɛː
-
  - ɛ̃
  - ɛ̃ː
-
  - ɪ
-
  - ɪ̃
-
  - ʊ
-
  - ʊ̃
