-
  - k
  - kʷ
  - c
  - cʰ
  - cʰː
  - ɡ
  - ɡʷ
  - ɟ
  - kʰ
  - kʰː
  - kʷː
  - k̚
  - k͈
  - k͈ʷ
  - k͈ː
  - c͈
  - c͈ː
-
  - m
  - mʲ
  - mː
  - mʲː
-
  - n
  - nː
-
  - ŋ
-
  - ɲ
-
  - p
  - pʲ
  - pʷ
  - b
  - bʲ
  - bʷ
  - pʰ
  - pʰː
  - pʲː
  - p̚
  - p͈
  - p͈ʲ
  - p͈ʷ
  - p͈ː
  - p͈ʲː
  - p͈ʷː
-
  - s
  - sʷ
  - sʷː
  - sː
  - sʰ
  - sʰː
  - s͈
  - s͈ʷ
  - s͈ː
  - ɕʰ
  - ɕʷ
  - ɕʰː
  - ɕʷː
  - ɕ͈
  - ɕ͈ː
-
  - t
  - tʲ
  - tʷ
  - tʷː
  - tʲː
  - d
  - dʲ
  - dʷ
  - tʰ
  - tʰː
  - t̚
  - t͈
  - t͈ʲ
  - t͈ː
  - t͈ʲː
-
  - tɕ
  - tɕʷ
  - tɕː
  - dʑ
  - dʑʷ
  - tɕʰ
  - tɕʰː
  - tɕʷː
  - tɕ͈
  - tɕ͈ʷ
  - tɕ͈ː
-
  - j
-
  - w
  - ɥ
-
  - h
  - ɦ
  - ɣ
  - x
  - ç
  - ʝ
  - β
  - βʷ
  - ɸ
  - ɸʷ
-
  - ɰ
-
  - ɾ
  - ɾʲ
  - ɾʷ
  - ɭ
  - ɭː
  - ʎ
  - ʎː
-
  - e
  - eː
-
  - i
  - iː
-
  - o
  - oː
-
  - u
  - uː
-
  - ɐ
-
  - ɛ
  - ɛː
-
  - ɨ
  - ɨː
-
  - ʌ
  - ʌː
