-
  - f
-
  - aj
  - aj˥
  - aj˥˩
  - aj˧˥
  - aj˧
  - aj˨˩˦
  - aj˩
-
  - aw
  - aw˥
  - aw˥˩
  - aw˧˥
  - aw˧
  - aw˨˩˦
  - aw˩
-
  - a
  - a˥
  - a˥˩
  - a˧˥
  - a˧
  - a˨˩˦
  - a˩
-
  - ej
  - ej˥
  - ej˥˩
  - ej˧˥
  - ej˧
  - ej˨˩˦
  - ej˩
-
  - e
  - e˥
  - e˥˩
  - e˧˥
  - e˧
  - e˨˩˦
  - e˩
-
  - i
  - i˥
  - i˥˩
  - i˧˥
  - i˧
  - i˨˩˦
  - i˩
  - j
-
  - k
-
  - kʰ
-
  - l
-
  - m
  - m̩
  - m̩˥
  - m̩˥˩
  - m̩˧˥
  - m̩˧
  - m̩˩
  - m̩˨˩˦
-
  - n
  - n̩
  - n̩˥˩
  - n̩˧˥
  - n̩˧
  - n̩˥
  - n̩˩
  - n̩˨˩˦
-
  - ow
  - ow˥
  - ow˥˩
  - ow˧˥
  - ow˧
  - ow˨˩˦
  - ow˩
-
  - o
  - o˥
  - o˥˩
  - o˧˥
  - o˧
  - o˨˩˦
  - o˩
-
  - p
-
  - pʰ
-
  - s
-
  - t
-
  - ts
-
  - tsʰ
-
  - tʰ
-
  - u
  - u˥
  - u˥˩
  - u˧˥
  - u˧
  - u˨˩˦
  - u˩
  - w
-
  - x
-
  - y
  - y˥
  - y˥˩
  - y˧˥
  - y˧
  - y˨˩˦
  - y˩
  - ɥ
-
  - z̩
  - z̩˥
  - z̩˥˩
  - z̩˦
  - z̩˧˥
  - z̩˧
  - z̩˨˩˦
  - z̩˩
-
  - ŋ
  - ŋ̍
  - ŋ̍˥
  - ŋ̍˧
  - ŋ̍˩
  - ŋ̍˥˩
  - ŋ̍˨˩˦
  - ŋ̍˧˥
-
  - ə
  - ə˥
  - ə˥˩
  - ə˧˥
  - ə˧
  - ə˨˩˦
  - ə˩
-
  - ɚ
  - ɚ˥
  - ɚ˥˩
  - ɚ˧˥
  - ɚ˧
  - ɚ˨˩˦
  - ɚ˩
-
  - ʂ
  - ɕ
-
  - ʈʂ
  - tɕ
-
  - ʈʂʰ
  - tɕʰ
-
  - ɻ
-
  - ʐ
  - ʐ̩
  - ʐ̩˥
  - ʐ̩˥˩
  - ʐ̩˧˥
  - ʐ̩˧
  - ʐ̩˨˩˦
  - ʐ̩˩
-
  - ʔ
