-
  - p
  - pː
-
  - b
-
  - t̪
  - t̪ː
-
  - d̪
-
  - ʈ
  - ʈː
-
  - ɖ
-
  - k
  - kː
-
  - ɡ
-
  - f
-
  - s
  - sː
-
  - ʂ
-
  - h
  - x
-
  - dʑ
-
  - m
  - mː
-
  - n
  - n̪
  - nː
-
  - ɳ
  - ɳː
-
  - ɲ
  - ɲː
-
  - ŋ
  - ŋː
-
  - ʋ
  - ʋː
-
  - r
-
  - ɾ
-
  - l
  - lː
-
  - ɻ
-
  - j
  - jː
-
  - ɐ
-
  - ɑː
-
  - ɛ
-
  - eː
-
  - iː
-
  - ɪ
-
  - o
  - oː
-
  - u
  - uː
-
  - ɯ
-
  - aj
-
  - aw
-
  - w
