-
  - aː˥˩
  - aː˦˥
  - aː˧
  - aː˨˩
  - aː˩˩˦
  - a˥˩
  - a˦˥
  - a˧
  - a˨˩
  - a˩˩˦
-
  - b
-
  - d
-
  - eː˥˩
  - eː˦˥
  - eː˧
  - eː˨˩
  - eː˩˩˦
  - e˥˩
  - e˦˥
  - e˧
  - e˨˩
  - e˩˩˦
-
  - f
-
  - h
-
  - ia˥˩
  - ia˦˥
  - ia˧
  - ia˨˩
  - ia˩˩˦
-
  - iː˥˩
  - iː˦˥
  - iː˧
  - iː˨˩
  - iː˩˩˦
  - i˥˩
  - i˦˥
  - i˧
  - i˨˩
  - i˩˩˦
-
  - j
-
  - k
-
  - kʰ
-
  - k̚
-
  - l
-
  - m
-
  - n
-
  - oː˥˩
  - oː˦˥
  - oː˧
  - oː˨˩
  - oː˩˩˦
  - o˥˩
  - o˦˥
  - o˧
  - o˨˩
  - o˩˩˦
-
  - p
-
  - pʰ
-
  - p̚
-
  - r
-
  - s
-
  - t
-
  - tɕ
-
  - tɕʰ
-
  - tʰ
-
  - t̚
-
  - ua˥˩
  - ua˦˥
  - ua˧
  - ua˨˩
  - ua˩˩˦
-
  - uː˥˩
  - uː˦˥
  - uː˧
  - uː˨˩
  - uː˩˩˦
  - u˥˩
  - u˦˥
  - u˧
  - u˨˩
  - u˩˩˦
-
  - w
-
  - ŋ
-
  - ɔː˥˩
  - ɔː˦˥
  - ɔː˧
  - ɔː˨˩
  - ɔː˩˩˦
  - ɔ˥˩
  - ɔ˦˥
  - ɔ˧
  - ɔ˨˩
  - ɔ˩˩˦
-
  - ɛː˥˩
  - ɛː˦˥
  - ɛː˧
  - ɛː˨˩
  - ɛː˩˩˦
  - ɛ˥˩
  - ɛ˦˥
  - ɛ˧
  - ɛ˨˩
  - ɛ˩˩˦
-
  - ɤː˥˩
  - ɤː˦˥
  - ɤː˧
  - ɤː˨˩
  - ɤː˩˩˦
  - ɤ˥˩
  - ɤ˦˥
  - ɤ˧
  - ɤ˨˩
  - ɤ˩˩˦
-
  - ɯa˥˩
  - ɯa˦˥
  - ɯa˧
  - ɯa˨˩
  - ɯa˩˩˦
-
  - ɯː˥˩
  - ɯː˦˥
  - ɯː˧
  - ɯː˨˩
  - ɯː˩˩˦
  - ɯ˥˩
  - ɯ˦˥
  - ɯ˧
  - ɯ˨˩
  - ɯ˩˩˦
-
  - ʔ
