channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - montreal-forced-aligner
  - sphinx
  - myst-parser
  - numpydoc
  - pydata-sphinx-theme
  - sphinx-design
  - kaldi =*=cpu*
  - pip:
      - sphinx-needs
      - sphinxcontrib-plantuml
