rules:
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'i̥'
  segment: i
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: i
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'i̥'
  segment: i
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: i
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'ɯ̥'
  segment: ɯ
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: ɯ
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'ɯ̥'
  segment: ɯ
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: ɯ
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'ɨ̥'
  segment: ɨ
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: ɨ
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'ɨ̥'
  segment: ɨ
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: ɨ
