rules:
- following_context: '[tpkc].*'
  preceding_context: ''
  replacement: ''
  segment: k̚
- following_context: '[tpkc].*'
  preceding_context: ''
  replacement: ''
  segment: p̚
- following_context: '[tpkc].*'
  preceding_context: ''
  replacement: ''
  segment: t̚
- following_context: '$'
  preceding_context: ''
  replacement: ''
  segment: k̚
- following_context: '$'
  preceding_context: ''
  replacement: ''
  segment: p̚
- following_context: '$'
  preceding_context: ''
  replacement: ''
  segment: t̚
- following_context: ''
  preceding_context: ''
  replacement: 'n'
  segment: 'n h'
- following_context: ''
  preceding_context: ''
  replacement: ''
  segment: ɦ
- following_context: ''
  preceding_context: '^'
  replacement: 'd'
  segment: 'n'
- following_context: ''
  preceding_context: '^'
  replacement: 'dʲ'
  segment: 'ɲ'
- following_context: ''
  preceding_context: '^'
  replacement: 'bʲ'
  segment: 'mʲ'
- following_context: ''
  preceding_context: ''
  replacement: 'ɲ'
  segment: 'n ʝ'
- following_context: ''
  preceding_context: ''
  replacement: 'dʑ'
  segment: 'dʲ'
- following_context: ''
  preceding_context: ''
  replacement: 'tɕʰ'
  segment: 'tʲ'
