rules:
- following_context: '$'
  preceding_context: ''
  replacement: ''
  segment: j
- following_context: ''
  preceding_context: ''
  replacement: 'ɳː'
  segment: n r
- following_context: ''
  preceding_context: ''
  replacement: 't̪ː'
  segment: ʈː ɾ
- following_context: ''
  preceding_context: ''
  replacement: 'ɾ'
  segment: r
- following_context: 'oː?'
  preceding_context: '^'
  replacement: 'w'
  segment: ''
- following_context: '[ɐɪɑaɛieuoɯ][jw]?ː?'
  preceding_context: '^'
  replacement: 'ʔ'
  segment: ''
- following_context: ''
  preceding_context: '^'
  replacement: 's'
  segment: tɕ
- following_context: 'ɛ'
  preceding_context: '^'
  replacement: 'j'
  segment: ''
- following_context: 'eː'
  preceding_context: '^'
  replacement: 'j'
  segment: ''
- following_context: '[ɐɪɑaɛieuoɯ][jw]?ː?'
  preceding_context: '[ɐɪɑaɛieuoɯ][jw]?ː?'
  replacement: 'ɣ'
  segment: ɡ
- following_context: '[ɐɪɑaɛieuoɯ][jw]?ː?'
  preceding_context: '[ɐɪɑaɛieuoɯ][jw]?ː?'
  replacement: 'β'
  segment: b
- following_context: '[ɐɪɑaɛieuoɯ][jw]?ː?'
  preceding_context: '[ɐɪɑaɛieuoɯ][jw]?ː?'
  replacement: 'ɽ'
  segment: ɖ
- following_context: '[ɐɪɑaɛieuoɯ][jw]?ː?'
  preceding_context: '[ɐɪɑaɛieuoɯ][jw]?ː?'
  replacement: 'ð'
  segment: d̪
